import = ["/home/nova/.config/alacritty/colors.toml", "/home/nova/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_title = true
#gtk_theme_variant = "dark"

[window.dimensions]
columns = 115
lines = 20

[window.padding]
x = 20
y = 20
